# Generated by Django 4.1.4 on 2023-05-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Recived', 'Recived'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], default='Recived', max_length=15),
        ),
    ]
