# Generated by Django 4.1.6 on 2023-04-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_account_first_name_remove_account_last_name'),
        ('store', '0006_product_product_id_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.seller'),
        ),
    ]
