# Generated by Django 4.1.6 on 2023-03-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_buyer_seller_alter_account_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='location',
        ),
    ]
