# Generated by Django 4.1.6 on 2023-03-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='user_image',
            field=models.ImageField(blank=True, default='images/profile/buyer/user-default.jpg', null=True, upload_to='profile/buyer'),
        ),
        migrations.AddField(
            model_name='seller',
            name='user_image',
            field=models.ImageField(blank=True, default='images/profile/seller/user-default.jpg', null=True, upload_to='profile/seller'),
        ),
    ]
