# Generated by Django 4.1.6 on 2023-03-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='user_image',
            field=models.ImageField(blank=True, default='profile/buyer/user-default.jpg', null=True, upload_to='profile/buyer'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user_image',
            field=models.ImageField(blank=True, default='profile/seller/user-default.jpg', null=True, upload_to='profile/seller'),
        ),
    ]
