# Generated by Django 4.1.6 on 2023-03-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_buyer_user_image_alter_seller_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='user_image',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user_image',
        ),
        migrations.AddField(
            model_name='buyer',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/buyer/user-default.png', null=True, upload_to='profile/buyer/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/buyer/user-default.png', null=True, upload_to='profile/seller/'),
        ),
    ]
