# Generated by Django 4.1.6 on 2023-03-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_buyer_user_image_remove_seller_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile/buyer/user-default.png', null=True, upload_to='profile/buyer/'),
        ),
    ]
