# Generated by Django 4.1.6 on 2023-04-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_deliverycompany_deliveryguy_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverycompany',
            name='location',
        ),
        migrations.RemoveField(
            model_name='deliveryguy',
            name='location',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='location',
        ),
    ]
