# Generated by Django 4.1.4 on 2023-04-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_deliverycompany_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryguy',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.deliverycompany'),
        ),
    ]
