# Generated by Django 4.1.4 on 2023-05-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_location_buyer_latitude_buyer_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
