# Generated by Django 4.1.4 on 2023-05-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_seller_location_deliveryguy_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='longitude',
        ),
        migrations.AddField(
            model_name='buyer',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
