# Generated by Django 4.1.4 on 2023-05-31 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_buyer_latitude_remove_buyer_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='username',
            new_name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='username',
        ),
    ]
