# Generated by Django 4.1.4 on 2023-05-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_first_name_deliverycompany_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='location',
        ),
    ]
