# Generated by Django 4.1.4 on 2023-06-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_deliveryguy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryguy',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='deliveryguy',
            name='completed_jobs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryguy',
            name='driven',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryguy',
            name='earnings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
