# Generated by Django 4.1.4 on 2023-06-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_deliveryguy_completed_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycompany',
            name='delivery_fee',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
