# Generated by Django 4.1.4 on 2023-06-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_deliverycompany_delivery_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverycompany',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='deliverycompany',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='deliveryguy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='deliveryguy',
            name='longitude',
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
