# Generated by Django 4.1.4 on 2023-06-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_deliverycompany_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='first_name',
            new_name='buisness_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_name',
        ),
    ]
