# Generated by Django 4.1.4 on 2023-06-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_rename_first_name_seller_buisness_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycompany',
            old_name='profile_image',
            new_name='verification_image',
        ),
    ]
