# Generated by Django 4.1.4 on 2023-06-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_rename_profile_image_deliverycompany_verification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryguy',
            name='completed_jobs',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
    ]
