# Generated by Django 4.1.4 on 2023-06-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_deliveryguy_completed_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is verified'),
        ),
    ]
