# Generated by Django 5.0 on 2023-12-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_account_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='longitude',
        ),
    ]
