# Generated by Django 4.1.4 on 2023-06-03 07:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_rename_payment_payment_methods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_Info',
            new_name='Company_Information',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Payment_Methods',
            new_name='Payment_Method',
        ),
    ]
