# Generated by Django 4.1.4 on 2023-06-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_company_info_company_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_method',
            name='included_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
