# Generated by Django 4.1.4 on 2023-03-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_payment_remove_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Delivred', 'Delivred')], default='New', max_length=10),
        ),
    ]
