# Generated by Django 4.1.4 on 2023-04-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='reciver_name',
        ),
    ]
