# Generated by Django 4.1.4 on 2023-04-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_first_name_order_reciver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
