# Generated by Django 4.1.4 on 2023-04-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_email_remove_order_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery',
            new_name='delivery_company',
        ),
    ]
