# Generated by Django 4.1.4 on 2023-05-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_status_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='payment',
        ),
        migrations.AddField(
            model_name='refund',
            name='total_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
