# Generated by Django 4.1.4 on 2023-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_refund_payment_refund_total_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='total_payment',
            field=models.FloatField(),
        ),
    ]
