# Generated by Django 4.1.4 on 2023-05-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_refund_total_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_qr_emailed',
            field=models.BooleanField(default=False),
        ),
    ]
