# Generated by Django 4.1.4 on 2023-06-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_orderedproduct_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='seller_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Paid', 'Paid')], default='Waiting', max_length=10),
        ),
    ]
